- hosts: localhost
#  strategy: debug
  vars:
   host: "192.168.122.70"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
#  - name: Upload python module wrkaround when pip is not an option.
#    copy: src=library/fortiosapi.py dest=/usr/local/lib/python2.7/dist-packages/fortiosapi.py
  - name: Try to pass cli cmd ssh
    fortiosconfig:
     action: "ssh"
     host:  "{{  host }}"  
     username: "{{  username}}"  
     password: "{{ password }}"  
     commands: |
               execute update-now
               get system status
               